version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.8.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
            - cypress-cache-{{ checksum "package-lock.json" }}
            - cypress-cache-{{ checksum ".circleci/config.yml" }}
      - run: npm install
      - run: npx cypress install
      - save_cache:
          key: cypress-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/Cypress
      - run: npm run test
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test_results
    working_directory: ~/repo
