version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.13.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
            - cypress-cache-{{ checksum "package-lock.json" }}
            - cypress-cache-{{ checksum ".circleci/config.yml" }}
      - run: npm install
      - run: npx cypress install
      - save_cache:
          key: cypress-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/Cypress
      - run: npm run test
    working_directory: ~/repo
